# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  front-end-build:
    docker:
      - image: hashimotorafa/tic_tac_toe-front_end
        auth:
          username: hashimotorafa
          password: $DOCKER_REGISTRY_PASSWORD
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  front-end-test:
    docker:
      - image: hashimotorafa/tic_tac_toe-front_end
        auth:
          username: hashimotorafa
          password: $DOCKER_REGISTRY_PASSWORD
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  front-end-audit:
    docker:
      - image: hashimotorafa/tic_tac_toe-front_end
        auth:
          username: hashimotorafa
          password: $DOCKER_REGISTRY_PASSWORD
    steps:
      - checkout
      - run: npm audit
workflows:
  tic-tac-toe:
    jobs:
      - front-end-build
      - front-end-test:
          requires:
            - front-end-build
      - front-end-audit:
          requires:
            - front-end-test
